def welcome():
    print("\n\n`7MM\"\"\"Mq.            `7MM\"\"\"Mq.  `7MM\"\"\"YMM   .M\"\"\"bgd MMP\"\"MM\"\"YMM")
    print("  MM   `MM.             MM   `MM.   MM    `7  ,MI    \"Y P'   MM   `7")
    print("  MM   ,M9 `7M'   `MF'  MM   ,M9    MM   d    `MMb.          MM")
    print("  MMmmdM9    VA   ,V    MMmmdM9     MMmmMM      `YMMNq.      MM")
    print("  MM          VA ,V     MM  YM.     MM   Y  , .     `MM      MM")
    print("  MM           VVV      MM   `Mb.   MM     ,M Mb     dM      MM")
    print(".JMML.         ,V     .JMML. .JMM..JMMmmmmMMM P\"Ybmmd\"     .JMML.")
    print("              ,V")
    print("           OOb\"\n\n")